-- 完整更新 SQL 脚本
-- 生成时间: 2026-05-06T20:01:12.856Z

-- 1. 添加 points 列（如果不存在）
ALTER TABLE xp_total ADD COLUMN IF NOT EXISTS points INTEGER DEFAULT 0;

-- 2. 清空旧的积分记录和兑换记录（可选，先备份）
-- 如果你不想清空旧数据，请注释掉下面两行
TRUNCATE TABLE point_transactions;
TRUNCATE TABLE redemption_requests;

-- 3. 更新 xp_total 表（总经验和可用积分）
UPDATE xp_total SET total_xp = 40, points = 40, nickname = '冃半' WHERE name = 'Ada';
UPDATE xp_total SET total_xp = 40, points = 40, nickname = '扭啊扭' WHERE name = 'Amelia';
UPDATE xp_total SET total_xp = 30, points = 30, nickname = '没奶油的奥利奥' WHERE name = 'Angela';
UPDATE xp_total SET total_xp = 50, points = 50, nickname = 'Siyue' WHERE name = 'April';
UPDATE xp_total SET total_xp = 30, points = 30, nickname = 'Flash' WHERE name = 'Barry';
UPDATE xp_total SET total_xp = 140, points = 140, nickname = '幼儿园高材生' WHERE name = 'Bryan';
UPDATE xp_total SET total_xp = 60, points = 60, nickname = 'Candy' WHERE name = 'Candy';
UPDATE xp_total SET total_xp = 30, points = 30, nickname = 'Carmen' WHERE name = 'Carmen';
UPDATE xp_total SET total_xp = 30, points = 30, nickname = '宫西西' WHERE name = 'CC';
UPDATE xp_total SET total_xp = 30, points = 30, nickname = '机智的小胖哥' WHERE name = 'Changliang';
UPDATE xp_total SET total_xp = 50, points = 50, nickname = '川川' WHERE name = 'Cody';
UPDATE xp_total SET total_xp = 50, points = 0, nickname = '漫野雏菊' WHERE name = 'Daisy Lu';
UPDATE xp_total SET total_xp = 50, points = 50, nickname = '宇宙当红炸子鸡😎' WHERE name = 'Danni';
UPDATE xp_total SET total_xp = 10, points = 10, nickname = '无锡荠菜馄饨' WHERE name = 'Dido';
UPDATE xp_total SET total_xp = 30, points = 30, nickname = 'déjà vu' WHERE name = 'DJ';
UPDATE xp_total SET total_xp = 50, points = 50, nickname = '时间管理大师' WHERE name = 'Dobby';
UPDATE xp_total SET total_xp = 30, points = 30, nickname = '千万别声张先生' WHERE name = 'Edward';
UPDATE xp_total SET total_xp = 40, points = 40, nickname = '金佰利' WHERE name = 'Gina';
UPDATE xp_total SET total_xp = 30, points = 30, nickname = 'Grace' WHERE name = 'Grace';
UPDATE xp_total SET total_xp = 30, points = 30, nickname = 'Heidi' WHERE name = 'Heidi';
UPDATE xp_total SET total_xp = 40, points = 40, nickname = '羊没吐气' WHERE name = 'Iris';
UPDATE xp_total SET total_xp = 60, points = 60, nickname = '森森' WHERE name = 'Jason';
UPDATE xp_total SET total_xp = 40, points = 40, nickname = '二朵龙' WHERE name = 'Jesse';
UPDATE xp_total SET total_xp = 30, points = 30, nickname = '阿油几亩菜' WHERE name = 'Jim';
UPDATE xp_total SET total_xp = 40, points = 40, nickname = '陶瓷女工' WHERE name = 'Joy';
UPDATE xp_total SET total_xp = 30, points = 30, nickname = 'すみません' WHERE name = 'Kevin';
UPDATE xp_total SET total_xp = 60, points = 10, nickname = '小黄努力减肥' WHERE name = 'Krystal';
UPDATE xp_total SET total_xp = 55, points = 5, nickname = '爆炸瓜' WHERE name = 'Laughing';
UPDATE xp_total SET total_xp = 30, points = 30, nickname = 'Lily' WHERE name = 'Lily';
UPDATE xp_total SET total_xp = 35, points = 35, nickname = '黎晚' WHERE name = 'Lori';
UPDATE xp_total SET total_xp = 30, points = 30, nickname = '马化藤' WHERE name = 'Max';
UPDATE xp_total SET total_xp = 30, points = 30, nickname = 'Mediha' WHERE name = 'Mediha';
UPDATE xp_total SET total_xp = 60, points = 60, nickname = '花果山小母猴' WHERE name = 'Moon';
UPDATE xp_total SET total_xp = 30, points = 30, nickname = 'QQ少爷' WHERE name = 'Nanyi';
UPDATE xp_total SET total_xp = 50, points = 50, nickname = '一团儿' WHERE name = 'Olivia';
UPDATE xp_total SET total_xp = 65, points = 65, nickname = '不是艺术家' WHERE name = 'Oscar';
UPDATE xp_total SET total_xp = 55, points = 55, nickname = '满山猴子我腚最红' WHERE name = 'Patrick';
UPDATE xp_total SET total_xp = 50, points = 50, nickname = 'Rik' WHERE name = 'Rik';
UPDATE xp_total SET total_xp = 30, points = 30, nickname = '陶喆演唱会抢票超人' WHERE name = 'Rita';
UPDATE xp_total SET total_xp = 60, points = 60, nickname = '艺臻' WHERE name = 'Serena';
UPDATE xp_total SET total_xp = 30, points = 30, nickname = '七七' WHERE name = 'Seven';
UPDATE xp_total SET total_xp = 60, points = 60, nickname = '于适的老公' WHERE name = 'Strange';
UPDATE xp_total SET total_xp = 30, points = 30, nickname = '大顺' WHERE name = 'Tina';
UPDATE xp_total SET total_xp = 30, points = 30, nickname = '山竹' WHERE name = 'Vicky';
UPDATE xp_total SET total_xp = 30, points = 30, nickname = '皮卡丨皮卡' WHERE name = 'Victor';
UPDATE xp_total SET total_xp = 50, points = 50, nickname = 'Vincent' WHERE name = 'Vincent';
UPDATE xp_total SET total_xp = 75, points = 75, nickname = '月野子' WHERE name = 'Xiaolan';
UPDATE xp_total SET total_xp = 45, points = 45, nickname = 'ya' WHERE name = 'Ya';
UPDATE xp_total SET total_xp = 30, points = 30, nickname = '3199' WHERE name = 'Yolanda';
UPDATE xp_total SET total_xp = 40, points = 40, nickname = 'YOYO' WHERE name = 'Yoyo';
UPDATE xp_total SET total_xp = 65, points = 65, nickname = '毛腿吴彦祖' WHERE name = 'Yulong';
UPDATE xp_total SET total_xp = 55, points = 5, nickname = '周芳菲' WHERE name = 'Zoe';
UPDATE xp_total SET total_xp = 10, points = 10, nickname = 'Zoey' WHERE name = 'Zoey';
UPDATE xp_total SET total_xp = 40, points = 40, nickname = '最好的地方II有我一票' WHERE name = 'Sally';
UPDATE xp_total SET total_xp = 45, points = 45, nickname = 'Daddy' WHERE name = 'Xiaoxiao';
UPDATE xp_total SET total_xp = 35, points = 35, nickname = '8low8lowme' WHERE name = 'Julia';
UPDATE xp_total SET total_xp = 40, points = 40, nickname = '正正' WHERE name = 'Vika';
UPDATE xp_total SET total_xp = 80, points = 30, nickname = '煮鱼' WHERE name = 'Alvin';
UPDATE xp_total SET total_xp = 50, points = 50, nickname = '你算哪头朱' WHERE name = 'Alicia';
UPDATE xp_total SET total_xp = 75, points = 25, nickname = '外国公主' WHERE name = 'Tracy';
UPDATE xp_total SET total_xp = 45, points = 45, nickname = '泡泡' WHERE name = 'Lucia';
UPDATE xp_total SET total_xp = 45, points = 45, nickname = '香蕉橙个菠萝' WHERE name = 'Kimi';

-- 4. 插入积分记录
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('April', 'Siyue', 20, 20, 'K-Lab', '2026-04-07', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Cody', '川川', 20, 20, 'K-Lab', '2026-04-07', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Rik', 'Rik', 20, 20, 'K-Lab', '2026-04-07', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Yulong', '毛腿吴彦祖', 20, 20, 'K-Lab', '2026-04-07', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Olivia', '一团儿', 20, 20, '默默奉献设计师', '2026-04-20', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Oscar', '不是艺术家', 20, 20, '默默奉献设计师', '2026-04-20', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Ada', '冃半', 10, 10, '新用户注册', '2026-04-21', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Ada', '冃半', 10, 20, 'Outing 九宫图', '2026-04-21', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Amelia', '扭啊扭', 10, 10, '新用户注册', '2026-04-21', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Amelia', '扭啊扭', 10, 20, 'Outing 九宫图', '2026-04-21', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Angela', '没奶油的奥利奥', 10, 10, '新用户注册', '2026-04-21', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Barry', 'Flash', 10, 10, '新用户注册', '2026-04-21', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Bryan', '幼儿园高材生', 10, 10, '新用户注册', '2026-04-21', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Candy', 'Candy', 10, 10, '新用户注册', '2026-04-21', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Candy', 'Candy', 10, 20, 'Outing 九宫图', '2026-04-21', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('CC', '宫西西', 10, 10, '新用户注册', '2026-04-21', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Changliang', '机智的小胖哥', 10, 10, '新用户注册', '2026-04-21', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Cody', '川川', 10, 30, '新用户注册', '2026-04-21', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Daisy Lu', '漫野雏菊', 10, 10, '新用户注册', '2026-04-21', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Danni', '宇宙当红炸子鸡😎', 10, 10, '新用户注册', '2026-04-21', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('DJ', 'déjà vu', 10, 10, '新用户注册', '2026-04-21', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Dobby', '时间管理大师', 10, 10, '新用户注册', '2026-04-21', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Gina', '金佰利', 10, 10, '新用户注册', '2026-04-21', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Gina', '金佰利', 10, 20, 'Outing 九宫图', '2026-04-21', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Grace', 'Grace', 10, 10, '新用户注册', '2026-04-21', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Iris', '羊没吐气', 10, 10, '新用户注册', '2026-04-21', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Iris', '羊没吐气', 10, 20, 'Outing 九宫图', '2026-04-21', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Jason', '森森', 10, 10, '新用户注册', '2026-04-21', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Jason', '森森', 10, 20, 'Outing 九宫图', '2026-04-21', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Jesse', '二朵龙', 10, 10, '新用户注册', '2026-04-21', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Jim', '阿油几亩菜', 10, 10, '新用户注册', '2026-04-21', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Joy', '陶瓷女工', 10, 10, '新用户注册', '2026-04-21', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Joy', '陶瓷女工', 10, 20, 'Outing 九宫图', '2026-04-21', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Krystal', '小黄努力减肥', 10, 10, '新用户注册', '2026-04-21', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Laughing', '爆炸瓜', 10, 10, '新用户注册', '2026-04-21', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Lori', '黎晚', 10, 10, '新用户注册', '2026-04-21', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Mediha', 'Mediha', 10, 10, '新用户注册', '2026-04-21', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Moon', '花果山小母猴', 10, 10, '新用户注册', '2026-04-21', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Moon', '花果山小母猴', 10, 20, 'Outing 九宫图', '2026-04-21', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Nanyi', 'QQ少爷', 10, 10, '新用户注册', '2026-04-21', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Olivia', '一团儿', 10, 30, '新用户注册', '2026-04-21', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Oscar', '不是艺术家', 10, 30, '新用户注册', '2026-04-21', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Patrick', '满山猴子我腚最红', 10, 10, '新用户注册', '2026-04-21', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Rik', 'Rik', 10, 30, '新用户注册', '2026-04-21', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Rita', '陶喆演唱会抢票超人', 10, 10, '新用户注册', '2026-04-21', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Sally', '最好的地方II有我一票', 10, 10, 'Outing 九宫图', '2026-04-21', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Serena', '艺臻', 10, 10, '新用户注册', '2026-04-21', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Seven', '七七', 10, 10, '新用户注册', '2026-04-21', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Strange', '于适的老公', 10, 10, '新用户注册', '2026-04-21', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Vicky', '山竹', 10, 10, '新用户注册', '2026-04-21', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Victor', '皮卡丨皮卡', 10, 10, '新用户注册', '2026-04-21', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Vincent', 'Vincent', 10, 10, '新用户注册', '2026-04-21', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Xiaolan', '月野子', 10, 10, '新用户注册', '2026-04-21', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Yolanda', '3199', 10, 10, '新用户注册', '2026-04-21', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Yulong', '毛腿吴彦祖', 10, 30, '新用户注册', '2026-04-21', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Zoe', '周芳菲', 10, 10, '新用户注册', '2026-04-21', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Bryan', '幼儿园高材生', 10, 20, 'Outing 九宫图', '2026-04-22', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Daisy Lu', '漫野雏菊', 10, 20, 'Outing 九宫图', '2026-04-22', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Jesse', '二朵龙', 10, 20, 'Outing 九宫图', '2026-04-22', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Oscar', '不是艺术家', 10, 40, 'Outing 九宫图', '2026-04-22', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Serena', '艺臻', 10, 20, 'Outing 九宫图', '2026-04-22', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Strange', '于适的老公', 10, 20, 'Outing 九宫图', '2026-04-22', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Vika', '正正', 10, 10, 'Outing 九宫图', '2026-04-22', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Xiaolan', '月野子', 10, 20, 'Outing 九宫图', '2026-04-22', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Xiaoxiao', 'Daddy', 10, 10, 'Outing 九宫图', '2026-04-22', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Yoyo', 'YOYO', 10, 10, 'Outing 九宫图', '2026-04-22', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Candy', 'Candy', 20, 40, 'DD 分享', '2026-04-24', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Bryan', '幼儿园高材生', 60, 80, '四封邮件的含金量', '2026-04-25', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Laughing', '爆炸瓜', 5, 15, '专业解答', '2026-04-25', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Oscar', '不是艺术家', 5, 45, ' 资讯分享', '2026-04-25', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Xiaoxiao', 'Daddy', 10, 20, '新用户注册', '2026-04-26', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('April', 'Siyue', 10, 30, '新用户注册', '2026-04-27', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Carmen', 'Carmen', 10, 10, '新用户注册', '2026-04-27', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Dido', '无锡荠菜馄饨', 10, 10, '新用户注册', '2026-04-27', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Edward', '千万别声张先生', 10, 10, '新用户注册', '2026-04-27', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Heidi', 'Heidi', 10, 10, '新用户注册', '2026-04-27', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Julia', '8low8lowme', 10, 10, '新用户注册', '2026-04-27', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Kevin', 'すみません', 10, 10, '新用户注册', '2026-04-27', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Lily', 'Lily', 10, 10, '新用户注册', '2026-04-27', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Max', '马化藤', 10, 10, '新用户注册', '2026-04-27', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Sally', '最好的地方II有我一票', 10, 20, '新用户注册', '2026-04-27', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Tina', '大顺', 10, 10, '新用户注册', '2026-04-27', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Xiaolan', '月野子', 15, 35, 'Peer Tips', '2026-04-27', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Ya', 'ya', 10, 10, '新用户注册', '2026-04-27', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Yoyo', 'YOYO', 10, 20, '新用户注册', '2026-04-27', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Zoey', 'Zoey', 10, 10, '新用户注册', '2026-04-27', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Bryan', '幼儿园高材生', 20, 100, 'DD 分享', '2026-04-28', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Alicia', '你算哪头朱', 10, 10, '新用户注册', '2026-04-29', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Alvin', '煮鱼', 10, 10, '新用户注册', '2026-04-29', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Alvin', '煮鱼', 15, 25, 'Good Idea', '2026-04-29', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Bryan', '幼儿园高材生', 5, 105, '认真学习 Town Hall', '2026-04-29', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Daisy Lu', '漫野雏菊', 5, 25, '认真学习 Town Hall', '2026-04-29', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Danni', '宇宙当红炸子鸡😎', 5, 15, '认真学习 Town Hall', '2026-04-29', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Julia', '8low8lowme', 5, 15, '认真学习 Town Hall', '2026-04-29', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Krystal', '小黄努力减肥', 15, 25, 'One Day Eexperience Sharing', '2026-04-29', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Laughing', '爆炸瓜', 15, 30, 'One Day Eexperience Sharing', '2026-04-29', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Lucia', '泡泡', 10, 10, '新用户注册', '2026-04-29', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Lucia', '泡泡', 15, 25, 'Good Idea', '2026-04-29', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Moon', '花果山小母猴', 20, 40, 'Shortcuts 入门', '2026-04-29', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Strange', '于适的老公', 5, 25, '认真学习 Town Hall', '2026-04-29', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Tracy', '外国公主', 10, 10, '新用户注册', '2026-04-29', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Vika', '正正', 10, 20, '新用户注册', '2026-04-29', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Xiaolan', '月野子', 15, 50, 'One Day Eexperience Sharing', '2026-04-29', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Xiaoxiao', 'Daddy', 5, 25, '认真学习 Town Hall', '2026-04-29', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Ya', 'ya', 15, 25, 'Peer Tips', '2026-04-29', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Zoe', '周芳菲', 5, 15, '认真学习 Town Hall', '2026-04-29', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Zoe', '周芳菲', 5, 20, '积极提交积分', '2026-04-29', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Zoe', '周芳菲', 15, 35, 'Peer Tips', '2026-04-29', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Alvin', '煮鱼', 5, 30, '认真学习 Town Hall', '2026-04-30', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Alvin', '煮鱼', 15, 45, 'Peer Tips', '2026-04-30', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Tracy', '外国公主', 5, 15, '认真学习 Town Hall', '2026-04-30', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Tracy', '外国公主', 40, 55, '发起 Peer Tips*8', '2026-04-30', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Xiaolan', '月野子', 5, 55, '认真学习 Town Hall', '2026-04-30', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Serena', '艺臻', 5, 25, '认真学习 Town Hall', '2026-05-02', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Serena', '艺臻', 15, 40, 'Peer Tips', '2026-05-02', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Alicia', '你算哪头朱', 5, 15, '认真学习 Town Hall', '2026-05-02', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Alicia', '你算哪头朱', 15, 30, 'Good Idea', '2026-05-02', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Dobby', '时间管理大师', 15, 25, 'Peer Tips', '2026-05-02', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Bryan', '幼儿园高材生', 15, 120, 'Acc 邮件分享', '2026-05-02', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Strange', '于适的老公', 15, 40, 'Peer Tips', '2026-05-02', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Ada', '冃半', 20, 40, '4月 Training 已完成', '2026-05-04', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Alicia', '你算哪头朱', 20, 50, '4月 Training 已完成', '2026-05-04', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Alvin', '煮鱼', 20, 65, '4月 Training 已完成', '2026-05-04', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Amelia', '扭啊扭', 20, 40, '4月 Training 已完成', '2026-05-04', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Angela', '没奶油的奥利奥', 20, 30, '4月 Training 已完成', '2026-05-04', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('April', 'Siyue', 20, 50, '4月 Training 已完成', '2026-05-04', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Barry', 'Flash', 20, 30, '4月 Training 已完成', '2026-05-04', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Bryan', '幼儿园高材生', 20, 140, '4月 Training 已完成', '2026-05-04', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Candy', 'Candy', 20, 60, '4月 Training 已完成', '2026-05-04', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Carmen', 'Carmen', 20, 30, '4月 Training 已完成', '2026-05-04', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('CC', '宫西西', 20, 30, '4月 Training 已完成', '2026-05-04', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Changliang', '机智的小胖哥', 20, 30, '4月 Training 已完成', '2026-05-04', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Cody', '川川', 20, 50, '4月 Training 已完成', '2026-05-04', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Daisy Lu', '漫野雏菊', 20, 45, '4月 Training 已完成', '2026-05-04', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Daisy Lu', '漫野雏菊', 5, 50, '推荐家人和朋友', '2026-05-04', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Danni', '宇宙当红炸子鸡😎', 20, 35, '4月 Training 已完成', '2026-05-04', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Danni', '宇宙当红炸子鸡😎', 15, 50, 'Peer Tips', '2026-05-04', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('DJ', 'déjà vu', 20, 30, '4月 Training 已完成', '2026-05-04', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Dobby', '时间管理大师', 20, 45, '4月 Training 已完成', '2026-05-04', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Edward', '千万别声张先生', 20, 30, '4月 Training 已完成', '2026-05-04', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Gina', '金佰利', 20, 40, '4月 Training 已完成', '2026-05-04', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Grace', 'Grace', 20, 30, '4月 Training 已完成', '2026-05-04', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Heidi', 'Heidi', 20, 30, '4月 Training 已完成', '2026-05-04', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Iris', '羊没吐气', 20, 40, '4月 Training 已完成', '2026-05-04', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Jason', '森森', 20, 40, '4月 Training 已完成', '2026-05-04', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Jason', '森森', 20, 60, '4月 Training 已完成', '2026-05-04', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Jesse', '二朵龙', 20, 40, '4月 Training 已完成', '2026-05-04', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Jim', '阿油几亩菜', 20, 30, '4月 Training 已完成', '2026-05-04', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Joy', '陶瓷女工', 20, 40, '4月 Training 已完成', '2026-05-04', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Julia', '8low8lowme', 20, 35, '4月 Training 已完成', '2026-05-04', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Kevin', 'すみません', 20, 30, '4月 Training 已完成', '2026-05-04', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Kimi', '香蕉橙个菠萝', 20, 20, '4月 Training 已完成', '2026-05-04', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Kimi', '香蕉橙个菠萝', 10, 30, '新用户注册', '2026-05-04', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Kimi', '香蕉橙个菠萝', 15, 45, 'Peer Tips', '2026-05-04', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Krystal', '小黄努力减肥', 20, 45, '4月 Training 已完成', '2026-05-04', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Laughing', '爆炸瓜', 20, 50, '4月 Training 已完成', '2026-05-04', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Lily', 'Lily', 20, 30, '4月 Training 已完成', '2026-05-04', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Lori', '黎晚', 20, 30, '4月 Training 已完成', '2026-05-04', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Lucia', '泡泡', 20, 45, '4月 Training 已完成', '2026-05-04', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Max', '马化藤', 20, 30, '4月 Training 已完成', '2026-05-04', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Mediha', 'Mediha', 20, 30, '4月 Training 已完成', '2026-05-04', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Moon', '花果山小母猴', 20, 60, '4月 Training 已完成', '2026-05-04', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Nanyi', 'QQ少爷', 20, 30, '4月 Training 已完成', '2026-05-04', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Olivia', '一团儿', 20, 50, '4月 Training 已完成', '2026-05-04', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Oscar', '不是艺术家', 20, 65, '4月 Training 已完成', '2026-05-04', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Patrick', '满山猴子我腚最红', 20, 30, '4月 Training 已完成', '2026-05-04', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Rik', 'Rik', 20, 50, '4月 Training 已完成', '2026-05-04', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Rita', '陶喆演唱会抢票超人', 20, 30, '4月 Training 已完成', '2026-05-04', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Sally', '最好的地方II有我一票', 20, 40, '4月 Training 已完成', '2026-05-04', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Serena', '艺臻', 20, 60, '4月 Training 已完成', '2026-05-04', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Seven', '七七', 20, 30, '4月 Training 已完成', '2026-05-04', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Strange', '于适的老公', 20, 60, '4月 Training 已完成', '2026-05-04', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Tina', '大顺', 20, 30, '4月 Training 已完成', '2026-05-04', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Tracy', '外国公主', 20, 75, '4月 Training 已完成', '2026-05-04', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Vicky', '山竹', 20, 30, '4月 Training 已完成', '2026-05-04', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Victor', '皮卡丨皮卡', 20, 30, '4月 Training 已完成', '2026-05-04', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Vika', '正正', 20, 40, '4月 Training 已完成', '2026-05-04', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Vincent', 'Vincent', 20, 30, '4月 Training 已完成', '2026-05-04', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Vincent', 'Vincent', 15, 45, 'Peer Tips', '2026-05-04', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Vincent', 'Vincent', 5, 50, '认真学习 Town Hall', '2026-05-04', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Xiaolan', '月野子', 20, 75, '4月 Training 已完成', '2026-05-04', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Xiaoxiao', 'Daddy', 20, 45, '4月 Training 已完成', '2026-05-04', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Ya', 'ya', 20, 45, '4月 Training 已完成', '2026-05-04', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Yolanda', '3199', 20, 30, '4月 Training 已完成', '2026-05-04', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Yoyo', 'YOYO', 20, 40, '4月 Training 已完成', '2026-05-04', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Yulong', '毛腿吴彦祖', 20, 50, '4月 Training 已完成', '2026-05-04', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Zoe', '周芳菲', 20, 55, '4月 Training 已完成', '2026-05-04', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Laughing', '爆炸瓜', 5, 55, '认真学习 Town Hall', '2026-05-04', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Lori', '黎晚', 5, 35, '认真学习 Town Hall', '2026-05-04', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Patrick', '满山猴子我腚最红', 15, 45, 'Peer Tips', '2026-05-04', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Patrick', '满山猴子我腚最红', 5, 50, '认真学习 Town Hall', '2026-05-04', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Patrick', '满山猴子我腚最红', 5, 55, '专业解答 & 资讯分享', '2026-05-04', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Yulong', '毛腿吴彦祖', 15, 65, 'Peer Tips', '2026-05-04', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Krystal', '小黄努力减肥', 15, 60, 'Peer Tips', '2026-05-04', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Dobby', '时间管理大师', 5, 50, '认真学习 Town Hall', '2026-05-05', 'auto_approved', 'system');
INSERT INTO point_transactions (user_name, user_nickname, change_amount, balance_after, reason, created_at, type, created_by) VALUES ('Alvin', '煮鱼', 15, 80, 'Peer Tips', '2026-05-06', 'auto_approved', 'system');

-- 5. 插入兑换记录
INSERT INTO redemption_requests (user_name, user_nickname, item_name, points_cost, created_at, status, reviewed_by, reviewed_at) VALUES ('Alvin', '煮鱼', '小礼物', 50, '2026-05-04', 'approved', 'system', '2026-05-04');
INSERT INTO redemption_requests (user_name, user_nickname, item_name, points_cost, created_at, status, reviewed_by, reviewed_at) VALUES ('Zoe', '周芳菲', '小礼物', 50, '2026-05-04', 'approved', 'system', '2026-05-04');
INSERT INTO redemption_requests (user_name, user_nickname, item_name, points_cost, created_at, status, reviewed_by, reviewed_at) VALUES ('Tracy', '外国公主', '小礼物', 50, '2026-05-04', 'approved', 'system', '2026-05-04');
INSERT INTO redemption_requests (user_name, user_nickname, item_name, points_cost, created_at, status, reviewed_by, reviewed_at) VALUES ('Daisy Lu', '漫野雏菊', '小礼物', 50, '2026-05-04', 'approved', 'system', '2026-05-04');
INSERT INTO redemption_requests (user_name, user_nickname, item_name, points_cost, created_at, status, reviewed_by, reviewed_at) VALUES ('Laughing', '爆炸瓜', '小礼物', 50, '2026-05-06', 'approved', 'system', '2026-05-06');
INSERT INTO redemption_requests (user_name, user_nickname, item_name, points_cost, created_at, status, reviewed_by, reviewed_at) VALUES ('Krystal', '小黄努力减肥', '小礼物', 50, '2026-05-06', 'approved', 'system', '2026-05-06');